# 服务器访问端口
server:
  port: 8080
# 数据库基本配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiahangchun
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true