#############################################
spring:
  profiles:
    active: dev
  http:
      encoding:
        charset: utf-8
        enabled: true
        force: true
        force-request: true
        force-response: true
banner:
  charset: UTF-8
  location: classpath:config/banner.txt



